twig:
    default_path: '%kernel.project_dir%/src/Frontend/Theme/Presentation'
    paths:
        '%kernel.project_dir%/src/Frontend': frontend
        '%kernel.project_dir%/src/Backend': backend

when@test:
    twig:
        strict_variables: true
