###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=modular-symfony-template
            - MYSQL_DATABASE=modular-symfony-template
            - MYSQL_USER=modular-symfony-template
            - MYSQL_PASSWORD=modular-symfony-template
        ports:
            - '18001:3306'

    mysql_test:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=modular-symfony-template
            - MYSQL_DATABASE=modular-symfony-template_test
            - MYSQL_USER=modular-symfony-template
            - MYSQL_PASSWORD=modular-symfony-template
        ports:
            - '18002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '18000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

    npm:
        image: node:latest
        working_dir: /application
        volumes:
            - '.:/application'
