controllers_frontend:
  resource: ../../src/Frontend/
  type: annotation

controllers_backend:
  resource: ../../src/Backend/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation