name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phpstan, phpcs
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHPCS
        run: phpcs src/

      - name: PHPStan
        run: phpstan analyse --level 5 --no-progress src/

      - name: Codesniffer
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          directory: src/

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Start docker compose stack
        run: docker-compose up -d

      - name: Install composer dependencies
        run: docker-compose exec -T php-fpm composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Migrate test database
        run: docker-compose exec -T php-fpm php bin/console --env=test d:m:m --no-interaction

      - name: Install npm packages
        run: docker-compose run npm npm install

      - name: Build frontends
        run: docker-compose run npm npm run build

      - name: Run tests
        run: docker-compose exec -T php-fpm php bin/phpunit

      - name: Stop docker compose stack
        run: docker-compose down
