name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Start docker compose stack
        run: docker-compose up -d

      - name: Install composer dependencies
        run: docker-compose exec -T php-fpm composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Cache composer dependencies
        uses: actions/cache@v3
        id: composer-dependencies
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Install npm packages
        run: docker-compose run npm npm install

      - name: Cache npm packages
        uses: actions/cache@v3
        id: npm-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build frontends
        run: docker-compose run npm npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./public/build/*

      - name: Stop docker compose stack
        run: docker-compose down

  quality:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v2

      - name: Start docker compose stack
        run: docker-compose up -d

      - uses: actions/cache@v3
        id: composer-dependencies
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Run PHPCS
        run: docker-compose exec -T php-fpm vendor/bin/phpcs src

      - name: Run PHPStan
        run: docker-compose exec -T php-fpm vendor/bin/phpstan analyse --level 5 src tests

      - name: Stop docker compose stack
        run: docker-compose down

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v2

      - name: Start docker compose stack
        run: docker-compose up -d

      - uses: actions/cache@v3
        id: composer-dependencies
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - uses: actions/cache@v3
        id: npm-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ./public/build/*

      - name: Migrate test database
        run: docker-compose exec -T php-fpm php bin/console --env=test d:m:m --no-interaction

      - name: Run tests
        run: docker-compose exec -T php-fpm php bin/phpunit

      - name: Stop docker compose stack
        run: docker-compose down
