name: Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Start docker compose stack
        run: docker-compose up -d

      - name: Install composer dependencies
        run: docker-compose exec php-fpm composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Migrate test database
        run: docker-compose exec php-fpm php bin/console --env=test d:m:m --no-interaction

      - name: Install npm packages
        run: docker-compose run npm npm install

      - name: Build frontends
        run: docker-compose run npm npm run build

      - name: Run tests
        run: docker-compose exec php-fpm php bin/phpunit

      - name: Stop docker compose stack
        run: docker-compose down
